name: Deploy StorageApp Frontend

on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      S3_BUCKET_NAME: client-my-drive
      CLOUDFRONT_DISTRIBUTION_ID: E20TISSBXDS97F
      VITE_GOOGLE_CLIENT_ID: 438673384254-15tpgatnhvig0v4fon193u623mv2tnvv.apps.googleusercontent.com
      VITE_BACKEND_BASE_URL: https://api.uvds.store

    steps:
      - name: Clone frontend repository
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: node version 
        run: node -v
